package view.Cliente;

import DAO.DAOCliente;
import model.Cliente;
import controller.ClienteController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;
import java.util.List;


public class ClienteListView extends JFrame {

    private JButton listarClientesButton;
    private JPanel UserForm;
    private JTextArea campoClientes;

    public ClienteListView() {
        add(UserForm);

        setTitle("Listagem de Usuários");
        setSize(400, 500);

        listarClientesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ClienteController controle = new ClienteController();
                try {
                    List<Cliente> listClientes = controle.listarCliente();
                    String[] listaClientes = new String[listClientes.size()];
                    int i = 0;

                    for (Cliente c : listClientes) {
                        listaClientes[i] = "\n- Cliente " + (i + 1) + "\n" + "Nome:" + c.getNome() + " CPF:" + c.getCpf() + " Telefone:" + c.getTel() + " Endereço: " + c.getEndereco();
                        i++;
                    }
                    campoClientes.setText(Arrays.toString(listaClientes).replace("[", "").replace(",", ""));
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        UserForm = new JPanel();
        UserForm.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        listarClientesButton = new JButton();
        listarClientesButton.setText("Listar Clientes");
        UserForm.add(listarClientesButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        campoClientes = new JTextArea();
        UserForm.add(campoClientes, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return UserForm;
    }

}
